### PR TITLE
Feat/message notifications

### PR DESCRIPTION
**Pull request by GustavoTCh**
Implement notifications

### CODE REVIEW

**Review by SamuelRioTz — APPROVED** [review]

**Comment by amenk** [comment]
Very interesting feature, thanks for implementing this. Can you eventually share some screenshots of the feature in action?

**Comment by amenk** [comment]
Do we have documentation on this? For the record:

* URL is configured in https://github.com/trufi-association/trufi-core/blob/5e1bced8a161dc7640527fe000f26bbd96b9a2a1/example/lib/main.dart#L53
* Sample content can be

```
{
    "title": "Title",
    "imageUrl": "https://placehold.co/800x450/png",
    "description": "Description![]()",
    "actionButton": {
        "name": "Responder ahora",
        "url": "https://www.example.com/"
    }
}
```
* Question: What is the []() for in the description?

**Comment by GustavoTCh** [comment]
@amenk at the moment, we haven't yet compiled documentation for this particular feature, and the notification is triggered when the app is closed and subsequently reopened.

- You're indeed using the correct method for setting a URL.

- When working with the example content, remember to incorporate the 'id' value to display the notification. Removing the 'id' will result in hiding the notification. Additionally, whenever you modify the notification, it's necessary to replace the 'id' with a new one.
```
{
    "id": "ID1",
    "title": "Title",
    "imageUrl": "https://placehold.co/800x450/png",
    "description": "Description![]()",
    "actionButton": {
        "name": "Responder ahora",
        "url": "https://www.example.com/"
    }
}
```

- I'm a bit unclear about your last question, but by utilizing the format `"[text](url)"` you can create text-based hyperlinks. As an illustration, you can write something like `"[Pull Request](https://github.com/trufi-association/trufi-core/pull/640)"` to generate a link to a pull request.

**Comment by GustavoTCh** [comment]
@amenk this is the example preview, for:
```
{
  "title": "Ayúdanos con tu participación para un estudio internacional!",
  "imageUrl": "https://api.busboy.app/static_files/notification-image.jpg",
  "description": "Con tu participación en la siguiente encuesta, ayudarás a las universidades de Hamburgo en Alemania y Coimbra en Portugal en la realización de un estudio internacional para mejorar la aplicación Trufi. Tómate 10-15 minutos y apóyanos!",
  "actionButton": {
    "name": "Responder ahora",
    "url": "https://www.soscisurvey.de/trufi/"
  }
}
```
Screenshot_1692639588

The title is a required value.

**Comment by amenk** [comment]
Cool, thank you very much I got it working - ID was missing in the JSON of the example, that's why it did not show at first.

**Pull request merged**
